server:
  port: 8282
#
#spring:
#  security:
#    user:
#      name: dilshan
#      password: abc123
#      roles: ADMIN,USER
#
#security:
#  oauth2:
#    client:
#      client-id:
#      client-secret: pin
#      access-token-validity-seconds: 3600
#      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
#      scope: READ,WRITE
#    authorization:
#      check-token-access: permitAll
