server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dilshanushara/config-store-2
          search-paths:
                - 'service-config/*service'
          default-label: main



